services:
  app:
    build: .
    container_name: project-named
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - .:/usr/src
      - node_modules:/usr/src/node_modules
    command: sh -c "npm run dev"

volumes:
  node_modules: